"""积分流水表。

只记流水，不记余额：余额是 `SUM(points)` 上去的派生值，落一张 balance 列会和流水
两处口径不一致（用户最怕的就是"扣了积分但流水对不上"）。余额那张表以后要做的话
应该是「余额快照 + 流水」，快照用于对账和加速查询，流水仍是唯一事实源。

字段落地的几处换算：

1. `id BigInt @default(autoincrement())` 落 `BigInteger` + `Identity()`，不用
   `autoincrement=True` 的隐式 SERIAL：流水表是全库增长最快的一张，int32 的
   21 亿在长期运行下不是安全余量；`Identity()` 是 SQL 标准写法，迁移文件里
   一眼能看出是 GENERATED ... AS IDENTITY 而不是 SERIAL。
2. `orderId` / `modelPointRuleId` **暂时只当普通 BigInt，不建外键**——
   订单表和模型计费规则表在这个仓库里都还不存在，现在建 FK 会直接引用不存在的表。
   等那两张表落地时补一个迁移加约束。这两列留了索引，将来 JOIN 用得上。
3. `changeType` / `source` 这类状态列延续项目惯例：`String` 列 + Python `StrEnum`，
   不用原生 Postgres ENUM（env.py 开了 compare_type，enum 类型会让 autogenerate
   反复产生噪音 diff）。
4. `PointType` 在 Prisma 里被注释掉了（`pointType` 和 `balanceAfter` 一起），
   这里也不建。等它定下来时是「加一列 + 一个枚举」的独立迁移。
5. 只有 `createdAt`，没有 `updatedAt`：流水是只追加的，不改不删。
   所以不继承 TimestampMixin。
"""

from datetime import datetime
from enum import StrEnum

from sqlalchemy import BigInteger, DateTime, ForeignKey, Identity, Index, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class PointChangeType(StrEnum):
    """积分变动方向。

    increase / adjust 是正数，decrease / expire 是负数——符号由 points 列的取值体现，
    这个枚举只说明"为什么变"。两者可能不一致（比如 admin_adjust 也可以是负数），
    所以别用 changeType 推符号，直接读 points。
    """

    increase = "increase"  # 增加
    decrease = "decrease"  # 扣减
    expire = "expire"  # 过期扣减
    adjust = "adjust"  # 人工调整


class PointSource(StrEnum):
    """流水来源。"""

    daily_login = "daily_login"  # 每日登录赠送
    monthly_fixed = "monthly_fixed"  # 每月固定积分
    purchase = "purchase"  # 购买积分
    usage = "usage"  # 使用消耗
    expire = "expire"  # 到期失效
    admin_adjust = "admin_adjust"  # 后台调整


class PointRecord(Base):
    """一条积分流水。"""

    __tablename__ = "point_records"

    # Identity() 生成 GENERATED BY DEFAULT AS IDENTITY。用 BY DEFAULT 而非 ALWAYS：
    # 数据迁移/回填时常常要显式指定 id，ALWAYS 会拒绝。
    id: Mapped[int] = mapped_column(BigInteger, Identity(), primary_key=True)

    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )

    # 两个外部实体都还没有对应的表，先占位不建 FK（见模块 docstring 第 2 点）
    order_id: Mapped[int | None] = mapped_column(BigInteger, default=None)
    model_point_rule_id: Mapped[int | None] = mapped_column(BigInteger, default=None)

    # 模型名快照：计费规则会改，事后对账要能看出当时用的是哪个模型
    model_name: Mapped[str | None] = mapped_column(String(128), default=None)

    # token 数：只有 usage 来源的流水才有值
    input_tokens: Mapped[int | None] = mapped_column(Integer, default=None)
    output_tokens: Mapped[int | None] = mapped_column(Integer, default=None)
    cache_hit_tokens: Mapped[int | None] = mapped_column(Integer, default=None)

    # 非空枚举列，两个 default 都给：server_default 让裸 SQL 和回填脚本也能 insert
    change_type: Mapped[str] = mapped_column(String(16))
    source: Mapped[str] = mapped_column(String(16))

    # 带符号：增加为正、消耗/过期为负。不设 CheckConstraint——人工调整（adjust）
    # 两个方向都可能出现，约束写死了反而要绕。
    points: Mapped[int] = mapped_column(Integer)

    # 这一笔积分的过期时刻。null = 永久有效（比如后台调整给的补偿分）
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)

    # Text 而非 String(n)：后台调整的备注长度不可控
    remark: Mapped[str | None] = mapped_column(Text, default=None)

    # 不继承 TimestampMixin：流水只追加，没有 updated_at
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (
        # 主业查询：某用户的流水按时间倒序翻页
        Index("ix_point_records_user_id_created_at", "user_id", "created_at"),
        # 过期扫描任务：where source='expire' 或按 expires_at 找待过期的分。
        # 挂 source 是让「按来源统计/筛选」也走得上索引。
        Index("ix_point_records_source_created_at", "source", "created_at"),
        # 单列索引：将来补 FK 时 Postgres 不会自动建，JOIN orders / 规则表用
        Index("ix_point_records_order_id", "order_id"),
        Index("ix_point_records_model_point_rule_id", "model_point_rule_id"),
        # 到期清理/统计「哪些分快过期了」：expires_at 大量为 NULL（永久分），
        # 用 partial index 把它排除掉，索引体积小很多
        Index(
            "ix_point_records_expires_at",
            "expires_at",
            postgresql_where="expires_at IS NOT NULL",
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<PointRecord id={self.id} user_id={self.user_id} "
            f"{self.source}/{self.change_type} points={self.points}>"
        )
