"""create users table

Revision ID: 35c5044b081b
Revises: 
Create Date: 2026-09-23 21:51:37.746686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c5044b081b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('uid', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('profile', sa.String(length=2048), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_email', 'users', ['email'], unique=True, postgresql_where='email IS NOT NULL')
    op.create_index('uq_users_phone', 'users', ['phone'], unique=True, postgresql_where='phone IS NOT NULL')
    op.create_index('uq_users_uid', 'users', ['uid'], unique=True, postgresql_where='uid IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_uid', table_name='users', postgresql_where='uid IS NOT NULL')
    op.drop_index('uq_users_phone', table_name='users', postgresql_where='phone IS NOT NULL')
    op.drop_index('uq_users_email', table_name='users', postgresql_where='email IS NOT NULL')
    op.drop_table('users')
    # ### end Alembic commands ###
