"""add point_records table

Revision ID: 70082553c125
Revises: 782c9e69b5d7
Create Date: 2026-09-28 17:59:12.564195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70082553c125'
down_revision: Union[str, Sequence[str], None] = '782c9e69b5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_records',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('model_point_rule_id', sa.BigInteger(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_hit_tokens', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_point_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_point_records'))
    )
    op.create_index('ix_point_records_expires_at', 'point_records', ['expires_at'], unique=False, postgresql_where='expires_at IS NOT NULL')
    op.create_index('ix_point_records_model_point_rule_id', 'point_records', ['model_point_rule_id'], unique=False)
    op.create_index('ix_point_records_order_id', 'point_records', ['order_id'], unique=False)
    op.create_index('ix_point_records_source_created_at', 'point_records', ['source', 'created_at'], unique=False)
    op.create_index('ix_point_records_user_id_created_at', 'point_records', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_point_records_user_id_created_at', table_name='point_records')
    op.drop_index('ix_point_records_source_created_at', table_name='point_records')
    op.drop_index('ix_point_records_order_id', table_name='point_records')
    op.drop_index('ix_point_records_model_point_rule_id', table_name='point_records')
    op.drop_index('ix_point_records_expires_at', table_name='point_records', postgresql_where='expires_at IS NOT NULL')
    op.drop_table('point_records')
    # ### end Alembic commands ###
