"""add sessions messages deployments

Revision ID: 782c9e69b5d7
Revises: 35c5044b081b
Create Date: 2026-09-28 16:59:17.143503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '782c9e69b5d7'
down_revision: Union[str, Sequence[str], None] = '35c5044b081b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_image', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('publish', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('views', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('preview_port', sa.Integer(), nullable=True),
    sa.Column('preview_status', sa.String(length=16), server_default='idle', nullable=False),
    sa.Column('preview_url', sa.String(length=2048), nullable=True),
    sa.Column('git_repo_name', sa.String(length=256), nullable=True),
    sa.Column('git_repo_url', sa.String(length=2048), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index('ix_sessions_user_id_is_deleted', 'sessions', ['user_id', 'is_deleted'], unique=False)
    op.create_index('ix_sessions_user_id_updated_at', 'sessions', ['user_id', 'updated_at'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('session_id', sa.String(length=12), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), server_default=sa.text('3000'), nullable=False),
    sa.Column('start_command', sa.String(length=512), server_default='bun run start', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('k8s_deployment', sa.String(length=255), nullable=True),
    sa.Column('k8s_service', sa.String(length=255), nullable=True),
    sa.Column('k8s_ingress', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('git_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_deployments_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_deployments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployments'))
    )
    op.create_index('ix_deployments_session_id', 'deployments', ['session_id'], unique=False)
    op.create_index('ix_deployments_user_id_created_at', 'deployments', ['user_id', 'created_at'], unique=False)
    op.create_index('uq_deployments_domain', 'deployments', ['domain'], unique=True)
    op.create_index('uq_deployments_name', 'deployments', ['name'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('session_id', sa.String(length=12), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('parts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('git_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_messages_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_session_id_created_at', 'messages', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_session_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('uq_deployments_name', table_name='deployments')
    op.drop_index('uq_deployments_domain', table_name='deployments')
    op.drop_index('ix_deployments_user_id_created_at', table_name='deployments')
    op.drop_index('ix_deployments_session_id', table_name='deployments')
    op.drop_table('deployments')
    op.drop_index('ix_sessions_user_id_updated_at', table_name='sessions')
    op.drop_index('ix_sessions_user_id_is_deleted', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
